project_id = "qhbrkcqopqjjaemifjtt"

[functions.ai-assistant]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.transcribe-media]
verify_jwt = true

[functions.generate-document]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
