import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        {
            clientId: 1,
            userId: 'user-123',
            title: 'Initial Consultation',
            date: '2024-05-15',
            time: '10:00',
            duration: 60,
            status: 'completed',
            notes: 'Discuss website redesign requirements and project scope',
            createdAt: new Date('2024-05-12').toISOString(),
            updatedAt: new Date('2024-05-12').toISOString(),
        },
        {
            clientId: 2,
            userId: 'user-123',
            title: 'Design Review',
            date: '2024-05-20',
            time: '14:00',
            duration: 90,
            status: 'completed',
            notes: 'Review mockups and discuss color scheme options',
            createdAt: new Date('2024-05-17').toISOString(),
            updatedAt: new Date('2024-05-17').toISOString(),
        },
        {
            clientId: 3,
            userId: 'user-123',
            title: 'Project Kickoff',
            date: '2024-05-25',
            time: '09:00',
            duration: 120,
            status: 'completed',
            notes: 'Full project kickoff meeting with stakeholders',
            createdAt: new Date('2024-05-20').toISOString(),
            updatedAt: new Date('2024-05-20').toISOString(),
        },
        {
            clientId: 4,
            userId: 'user-123',
            title: 'Quick Check-in',
            date: '2024-05-28',
            time: '11:30',
            duration: 30,
            status: 'completed',
            notes: 'Brief status update on development progress',
            createdAt: new Date('2024-05-24').toISOString(),
            updatedAt: new Date('2024-05-24').toISOString(),
        },
        {
            clientId: 5,
            userId: 'user-123',
            title: 'Budget Discussion',
            date: '2024-05-30',
            time: '15:00',
            duration: 60,
            status: 'cancelled',
            notes: 'Discuss additional features and budget implications',
            createdAt: new Date('2024-05-26').toISOString(),
            updatedAt: new Date('2024-05-29').toISOString(),
        },
        {
            clientId: 6,
            userId: 'user-123',
            title: 'Content Strategy Workshop',
            date: '2024-06-03',
            time: '10:00',
            duration: 120,
            status: 'rescheduled',
            notes: 'Workshop to define content structure and SEO strategy',
            createdAt: new Date('2024-05-28').toISOString(),
            updatedAt: new Date('2024-06-01').toISOString(),
        },
        {
            clientId: 7,
            userId: 'user-123',
            title: 'Development Sprint Review',
            date: '2024-06-10',
            time: '13:00',
            duration: 90,
            status: 'scheduled',
            notes: 'Review completed features and plan next sprint',
            createdAt: new Date('2024-06-05').toISOString(),
            updatedAt: new Date('2024-06-05').toISOString(),
        },
        {
            clientId: 8,
            userId: 'user-123',
            title: 'Status Update',
            date: '2024-06-15',
            time: '14:30',
            duration: 30,
            status: 'scheduled',
            notes: null,
            createdAt: new Date('2024-06-10').toISOString(),
            updatedAt: new Date('2024-06-10').toISOString(),
        },
        {
            clientId: 9,
            userId: 'user-123',
            title: 'User Testing Session',
            date: '2024-06-20',
            time: '09:30',
            duration: 90,
            status: 'scheduled',
            notes: 'Conduct usability testing with client team',
            createdAt: new Date('2024-06-12').toISOString(),
            updatedAt: new Date('2024-06-12').toISOString(),
        },
        {
            clientId: 10,
            userId: 'user-123',
            title: 'Final Presentation',
            date: '2024-07-05',
            time: '10:00',
            duration: 120,
            status: 'scheduled',
            notes: 'Present final deliverables and conduct handover',
            createdAt: new Date('2024-06-28').toISOString(),
            updatedAt: new Date('2024-06-28').toISOString(),
        },
        {
            clientId: 1,
            userId: 'user-123',
            title: 'Maintenance Planning',
            date: '2024-07-12',
            time: '11:00',
            duration: 60,
            status: 'scheduled',
            notes: 'Discuss ongoing maintenance and support options',
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        {
            clientId: 3,
            userId: 'user-123',
            title: 'Post-Launch Review',
            date: '2024-06-08',
            time: '16:00',
            duration: 60,
            status: 'cancelled',
            notes: null,
            createdAt: new Date('2024-06-03').toISOString(),
            updatedAt: new Date('2024-06-07').toISOString(),
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});