import { db } from '@/db';
import { receipts } from '@/db/schema';

async function main() {
    const sampleReceipts = [
        // Supplies (5 records)
        {
            vendor: 'Office Depot',
            amount: 127.50,
            category: 'supplies',
            date: '2024-01-15',
            fileUrl: 'https://storage.example.com/receipts/receipt-001.pdf',
            notes: 'Office supplies for Q1 - printer paper, pens, folders',
            userId: 'user-123',
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
            updatedAt: new Date('2024-01-15T10:30:00').toISOString(),
        },
        {
            vendor: 'Staples',
            amount: 89.99,
            category: 'supplies',
            date: '2024-02-03',
            fileUrl: null,
            notes: 'Desk organizers and filing supplies',
            userId: 'user-123',
            createdAt: new Date('2024-02-03T14:20:00').toISOString(),
            updatedAt: new Date('2024-02-03T14:20:00').toISOString(),
        },
        {
            vendor: 'Amazon Business',
            amount: 245.78,
            category: 'supplies',
            date: '2024-03-12',
            fileUrl: 'https://storage.example.com/receipts/receipt-002.pdf',
            notes: 'Bulk order: notebooks, sticky notes, markers',
            userId: 'user-123',
            createdAt: new Date('2024-03-12T09:15:00').toISOString(),
            updatedAt: new Date('2024-03-12T09:15:00').toISOString(),
        },
        {
            vendor: 'Best Buy Business',
            amount: 156.40,
            category: 'supplies',
            date: '2024-04-08',
            fileUrl: null,
            notes: 'USB drives and external hard drive',
            userId: 'user-123',
            createdAt: new Date('2024-04-08T16:45:00').toISOString(),
            updatedAt: new Date('2024-04-08T16:45:00').toISOString(),
        },
        {
            vendor: 'Office Max',
            amount: 73.25,
            category: 'supplies',
            date: '2024-05-20',
            fileUrl: 'https://storage.example.com/receipts/receipt-003.pdf',
            notes: 'Printer ink cartridges',
            userId: 'user-123',
            createdAt: new Date('2024-05-20T11:00:00').toISOString(),
            updatedAt: new Date('2024-05-20T11:00:00').toISOString(),
        },
        // Software (4 records)
        {
            vendor: 'Adobe Creative Cloud',
            amount: 54.99,
            category: 'software',
            date: '2024-01-01',
            fileUrl: null,
            notes: 'Monthly subscription for design tools',
            userId: 'user-123',
            createdAt: new Date('2024-01-01T08:00:00').toISOString(),
            updatedAt: new Date('2024-01-01T08:00:00').toISOString(),
        },
        {
            vendor: 'Microsoft 365',
            amount: 12.99,
            category: 'software',
            date: '2024-02-15',
            fileUrl: null,
            notes: 'Monthly business subscription',
            userId: 'user-123',
            createdAt: new Date('2024-02-15T08:00:00').toISOString(),
            updatedAt: new Date('2024-02-15T08:00:00').toISOString(),
        },
        {
            vendor: 'Figma',
            amount: 15.00,
            category: 'software',
            date: '2024-03-05',
            fileUrl: 'https://storage.example.com/receipts/receipt-004.pdf',
            notes: 'Professional plan for design collaboration',
            userId: 'user-123',
            createdAt: new Date('2024-03-05T08:00:00').toISOString(),
            updatedAt: new Date('2024-03-05T08:00:00').toISOString(),
        },
        {
            vendor: 'GitHub Pro',
            amount: 7.00,
            category: 'software',
            date: '2024-04-10',
            fileUrl: null,
            notes: 'Monthly subscription for private repositories',
            userId: 'user-123',
            createdAt: new Date('2024-04-10T08:00:00').toISOString(),
            updatedAt: new Date('2024-04-10T08:00:00').toISOString(),
        },
        // Travel (5 records)
        {
            vendor: 'United Airlines',
            amount: 487.50,
            category: 'travel',
            date: '2024-01-22',
            fileUrl: 'https://storage.example.com/receipts/receipt-005.pdf',
            notes: 'Flight to client meeting in Chicago',
            userId: 'user-123',
            createdAt: new Date('2024-01-22T06:30:00').toISOString(),
            updatedAt: new Date('2024-01-22T06:30:00').toISOString(),
        },
        {
            vendor: 'Uber',
            amount: 34.75,
            category: 'travel',
            date: '2024-02-10',
            fileUrl: null,
            notes: 'Airport transfer',
            userId: 'user-123',
            createdAt: new Date('2024-02-10T19:45:00').toISOString(),
            updatedAt: new Date('2024-02-10T19:45:00').toISOString(),
        },
        {
            vendor: 'Marriott Hotel',
            amount: 189.00,
            category: 'travel',
            date: '2024-03-18',
            fileUrl: 'https://storage.example.com/receipts/receipt-006.pdf',
            notes: 'Business conference accommodation',
            userId: 'user-123',
            createdAt: new Date('2024-03-18T15:00:00').toISOString(),
            updatedAt: new Date('2024-03-18T15:00:00').toISOString(),
        },
        {
            vendor: 'Airbnb',
            amount: 225.00,
            category: 'travel',
            date: '2024-04-25',
            fileUrl: null,
            notes: 'Extended stay for project work',
            userId: 'user-123',
            createdAt: new Date('2024-04-25T14:00:00').toISOString(),
            updatedAt: new Date('2024-04-25T14:00:00').toISOString(),
        },
        {
            vendor: 'Enterprise Rent-A-Car',
            amount: 98.50,
            category: 'travel',
            date: '2024-05-14',
            fileUrl: 'https://storage.example.com/receipts/receipt-007.pdf',
            notes: 'Car rental for client site visits',
            userId: 'user-123',
            createdAt: new Date('2024-05-14T09:00:00').toISOString(),
            updatedAt: new Date('2024-05-14T09:00:00').toISOString(),
        },
        // Meals (4 records)
        {
            vendor: 'Starbucks',
            amount: 17.45,
            category: 'meals',
            date: '2024-01-28',
            fileUrl: null,
            notes: 'Coffee meeting with prospective client',
            userId: 'user-123',
            createdAt: new Date('2024-01-28T09:30:00').toISOString(),
            updatedAt: new Date('2024-01-28T09:30:00').toISOString(),
        },
        {
            vendor: 'The Capital Grille',
            amount: 178.90,
            category: 'meals',
            date: '2024-03-07',
            fileUrl: 'https://storage.example.com/receipts/receipt-008.pdf',
            notes: 'Client dinner - contract signing celebration',
            userId: 'user-123',
            createdAt: new Date('2024-03-07T19:30:00').toISOString(),
            updatedAt: new Date('2024-03-07T19:30:00').toISOString(),
        },
        {
            vendor: 'Panera Bread',
            amount: 28.50,
            category: 'meals',
            date: '2024-04-15',
            fileUrl: null,
            notes: 'Working lunch with team',
            userId: 'user-123',
            createdAt: new Date('2024-04-15T12:15:00').toISOString(),
            updatedAt: new Date('2024-04-15T12:15:00').toISOString(),
        },
        {
            vendor: 'Local Coffee Shop',
            amount: 12.75,
            category: 'meals',
            date: '2024-05-30',
            fileUrl: null,
            notes: 'Quick meeting with freelancer',
            userId: 'user-123',
            createdAt: new Date('2024-05-30T10:00:00').toISOString(),
            updatedAt: new Date('2024-05-30T10:00:00').toISOString(),
        },
        // Utilities (2 records)
        {
            vendor: 'Comcast Business',
            amount: 89.99,
            category: 'utilities',
            date: '2024-02-01',
            fileUrl: 'https://storage.example.com/receipts/receipt-009.pdf',
            notes: 'Monthly business internet service',
            userId: 'user-123',
            createdAt: new Date('2024-02-01T08:00:00').toISOString(),
            updatedAt: new Date('2024-02-01T08:00:00').toISOString(),
        },
        {
            vendor: 'Verizon Business',
            amount: 75.00,
            category: 'utilities',
            date: '2024-03-15',
            fileUrl: null,
            notes: 'Monthly business phone bill',
            userId: 'user-123',
            createdAt: new Date('2024-03-15T08:00:00').toISOString(),
            updatedAt: new Date('2024-03-15T08:00:00').toISOString(),
        },
    ];

    await db.insert(receipts).values(sampleReceipts);
    
    console.log('✅ Receipts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});